// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnmmnjsuutssfadkoede.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNubW1uanN1dXRzc2ZhZGtvZWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjUxNjcsImV4cCI6MjA3MDQwMTE2N30.FSqfo_qfzy8a2OqcJAe37sA9JWQ4L5ngZi7O3J3t4Uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});